name: CI

on:
  push:
  # pull_request: # Comment this out, because we only want CI run for push's.
  schedule:
    - cron: '0 6 * * 1'  # Every monday 6 AM

jobs:
  build:
    # TODO: Get the Windows builds working...
    # continue-on-error: ${{ matrix.os.windows-latest }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # os: [ubuntu-latest, macos-latest]
        crystal: [null]
        include:
          - os: ubuntu-latest
            crystal: nightly
    runs-on: ${{matrix.os}}

    steps:
      # - name: Configure Git
      #   run: |
      #     git config --global user.email "drhuffman12@gmail.com"
      #     git config --global user.name "Daniel Huffman"
      #     git config --global column.ui always
      #     git config --global core.autocrlf false
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: ${{matrix.crystal}}

      - name: Download source
        uses: actions/checkout@v2

      - name: Build
        # run: shards install --ignore-crystal-version --skip-postinstall
        # run: shards install --ignore-crystal-version --without-development
        # run: shards install --ignore-crystal-version
        # run: shards install --ignore-crystal-version --skip-postinstall
        # run: shards install --ignore-crystal-version && shards build
        # run: shards install
        run: shards install --skip-postinstall

      - name: Test
        run: crystal spec

      ## The below parts should always pass on Linux, but might not pass (yet) on other platforms
      ## ... so these are moved to the 'coverage_etc' section further below.
      # - name: Check code coverage
      #   # run: .github/workflows/coverage.sh 50
      #   run: .github/workflows/coverage.sh 90
      #   # run: bin/crystal-coverage

      # - name: Check formatting
      #   run: crystal tool format --check src spec

  once_coverage_etc:
    # We could run coverage, etc on all OS's, but we really only need to do so on one OS,
    #   so, we'll go with the most Crystal-supported OS.
    # Also, these 'steps' should always pass on Linux, but might not pass (yet) on other platforms; e.g.:
    #   * Windows doesn't normally come with `make, so using `make bin` (for dependencies) break the Windows builds.
    # GOAL: Re-evaluate every so often and move applicable 'steps' up into 'build' job as applicable.
    runs-on: ubuntu-latest
    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: ${{matrix.crystal}}

      - name: Download source
        uses: actions/checkout@v2

      - name: Build
        # run: shards install --ignore-crystal-version --skip-postinstall
        # run: shards install --ignore-crystal-version --without-development
        run: shards install

      - name: Check code coverage
        # run: bin/crystal-coverage # TODO: Get min-cov param/feature added
        run: .github/workflows/coverage.sh 50 # Low min-cove to help pass CI
        # run: .github/workflows/coverage.sh 90 # High min-cove to help fail CI

      - name: Check formatting
        run: crystal tool format --check src spec

      # - name: Check style/etc
      #   run: crystal bin/ameba.cr

  once_docs:
    # We could build the doc's on all OS's, but we really only need doc's built once.
    # So, we'll go with the most Crystal-supported OS.
    runs-on: ubuntu-latest
    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: ${{matrix.crystal}}

      - name: Download source
        uses: actions/checkout@v2

      - name: Build
        # run: shards install --ignore-crystal-version --skip-postinstall
        # run: shards install --ignore-crystal-version --without-development
        run: shards install

      - name: Docs
        # run: crystal docs
        run: .github/workflows/regen_docs

  # docs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download source
  #       uses: actions/checkout@v2
  #     - name: Build docs
  #       run: crystal docs